In [2]:
from zipfile import ZipFile
# import scikit-iag
import numpy as np
import matplotlib.pyplot as plt
import glob 
from skimage import io
from skimage import data, color
from skimage.transform import hough_circle, hough_circle_peaks
from skimage.feature import canny
from skimage.draw import circle_perimeter
from skimage.util import img_as_ubyte
import cv2
import pandas as pd

def data_prep(filename):
    data = {'images':dict(),'description':dict()}
    zf = ZipFile(filename)
    split_value = []
    for i in range(len(zf.namelist())):
        current = zf.namelist()[i]
        imagelist = []
        if(".tiff" in current):
            split_value = current.split('/')
            if split_value[1] not in data['images'].keys():
                data['images'].update({split_value[1]:[]})
            data['images'][split_value[1]].append(current)
        elif(".txt" in current):
            split_value = current.split('/')
            if split_value[1] not in data['description']:
                data['description'].update({split_value[1]:list(pd.DataFrame())})
            file = zf.open(current)
            df = pd.read_csv(file, sep="\t", header=None,names=['attributes','type','value'])
            for k in range(0,len(df),55):
                data['description'][split_value[1]].append(df[k:k+55])
    zf.close()
    return data

In [3]:
gallery = data_prep('dataset\Zip Dataset\LG2200-2008-03-11_13.zip')
probe_1 = data_prep('dataset\Zip Dataset\LG2200-2010-04-27_29.zip')
probe_2 = data_prep('dataset\Zip Dataset\LG4000-2010-04-27_29.zip')
print(gallery['images'].keys())
print('\n',gallery['description'].keys())

print('\n',gallery['images']['02463'][0])

dict_keys(['02463', '04233', '04252', '04261', '04267', '04327', '04385', '04394', '04397', '04470', '04537', '04629', '04815', '04851', '04888', '04917', '05015', '05028', '05033', '05044', '05136', '05156', '05176', '05186', '05191', '05204', '05213', '05232', '05244', '05248', '05256', '05271', '05284', '05288', '05289', '05290', '05292', '05298', '05300', '05301', '05303', '05304', '05305', '05306', '05308', '05310', '05314', '05317', '05320', '05321', '05324', '05337', '05341', '05344', '05355', '05366', '05368', '05379', '05386', '05392', '05399', '05401', '05405', '05406', '05407', '05408', '05409', '05412', '05415', '05430', '05441', '05442', '05444', '05445', '05447', '05448', '05450', '05454', '05455', '05456', '05457', '05459', '05460', '05461', '05462', '05463', '05465', '05466'])

 dict_keys(['02463', '04233', '04252', '04261', '04267', '04327', '04385', '04394', '04397', '04470', '04537', '04629', '04815', '04851', '04888', '04917', '05015', '05028', '05033', '05044', '05136', '05156', '05176', '05186', '05191', '05204', '05213', '05232', '05244', '05248', '05256', '05271', '05284', '05288', '05289', '05290', '05292', '05298', '05300', '05301', '05303', '05304', '05305', '05306', '05308', '05310', '05314', '05317', '05320', '05321', '05324', '05337', '05341', '05344', '05355', '05366', '05368', '05379', '05386', '05392', '05399', '05401', '05405', '05406', '05407', '05408', '05409', '05412', '05415', '05430', '05441', '05442', '05444', '05445', '05447', '05448', '05450', '05454', '05455', '05456', '05457', '05459', '05460', '05461', '05462', '05463', '05465', '05466'])

 2008-03-11_13/02463/02463d1914.tiff

In [4]:
gallery['description']['02463'][0]

,attributes,type,value
0,id,numeric,185614
1,recordingid,string,nd5R68398
2,shotid,string,2008_071_021_L_1_4T-lg2200.tiff
3,sequenceid,string,02463d1914
4,date,string,2008-03-11 00:00:00
5,format,string,tiff
6,subjectid,string,nd1S02463
7,eye,string,Right
8,color,string,Brown
9,pose,numeric,0
10,motion,string,Still
11,treatment,string,No
12,glasses,string,No
13,collectionid,string,nd1C00013
14,stageid,string,nd1T00014
15,environmentid,string,nd1E00074
16,sensorid,string,nd1N00006
17,illuminantid,string,"nd1I00015,stdI00002"
18,illuminantid1,string,nd1I00012
19,weather,string,Inside
20,shot,numeric,2
21,state,string,enrolled
22,fileid,numeric,229172
23,by_user,string,flynn
24,lastcheck,string,2008-08-17 10:52:35
25,date_added,string,2008-08-12 17:02:29
26,added_by,string,dthomas4
27,temp_collectionid,string,1218574717
28,contacts,string,No
29,contacts_texture,string,No
30,contacts_toric,string,No
31,contacts_cosmetic,string,No
32,gender,string,Male
33,YOB,numeric,1956
34,race,string,White
35,fileid,numeric,229172
36,userkey,string,2008_071_021_L_1_4T-lg2200.tiff
37,checksum,string,95ac561a31b60480026873050834b615
38,extension,string,tiff
39,size,numeric,307872
40,lastcheck,string,2011-03-17 04:51:18
41,rank,numeric,0
42,fstate,string,ok
43,replicaid,numeric,1850140
44,fileid,numeric,229172
45,host,string,sc0-12.cse.nd.edu
46,path,string,/bxgrid/7/1/229172_1850140.tiff
47,state,string,ok
48,lastcheck,string,2011-03-17 04:51:18
49,name,string,sc0-12.cse.nd.edu
50,state,string,ok
51,groupid,numeric,1
52,r_priority,numeric,1
53,format,string,tiff
54,file,file,/afs/crc.nd.edu/user/a/asgroi/challenge/LG2200...